.eslintrc.js, .prettierignore, .vscode/settings.json, src/App.tsx, src/ts_common.ts
code formatting settings have been updated for future code reviews. Unused code will be automatically deleted when you save it, and imported files will be organized and formatted by name.
=> add vscode settings and eslint 

src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/styles/_tables.scss
Fixing browser validation errors
=> Cat pre demo fix

src/apis/continueRequest.ts, src/apis/scimGroupsRequest.ts, src/apis/scimUsersRequest.ts, src/components/Callback.tsx, src/components/Footer.tsx, src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/components/StartSession.tsx, src/initLocalStorage.ts, src/slices/getGroups.ts
Now we can obtain a real access token through login eduID. Please check whether changing the language still maintains the availability of the access token (no console log error indicating a missing access token)
=> Eunju login eduid

src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/styles/_groupManagement.scss, src/translation/extractedMessages.json
Added breaf summary of functionality, 
show more/less descriptive links above form and table with instructions, 
copy edits to match new features.
=> Cat show hide

src/components/MembersList.tsx
- adapt to backend new implementation, that removes itself the User from the Group
- send a DELETE only when the previous has got a response
=> New removeSelectedUser()

src/apis/continueRequest.ts, src/components/Callback.tsx, src/components/GroupManagement.tsx, src/components/Header.tsx, src/slices/getLoggedInUserInfo.ts, src/store.ts
- add redirect to the first page to get the access token when the user does not have a token on the scam page. 
- add the users email in the header
- add display name in the main
=> Add the users email in the header and display name in main(section)

src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/translation/extractedMessages.json
Edited copy: student to account
=> Cat account copy

src/components/GroupManagement.tsx
Avoid to create "Given name" and "Surname" made only of spaces. We have not implemented "edit" to change eventually the name or surname afterwards
=> validate if input is only spaces

src/components/Footer.tsx, src/components/StartSession.tsx, src/translation/extractedMessages.json
Added translated text and link, to be edited later if needed.
=> info text on redirect/landing

src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/styles/_buttons.scss, src/styles/_groupManagement.scss, src/styles/_typography.scss, src/translation/extractedMessages.json
Updated/added copy in lead and instructions
Added translatable text for form controls
Spacing edits in forms, and lists
Tighter buttons, more coherence in hover and type and size
Slightly reorganised form controls
=> Cat table header

src/apis/scim/error.ts, src/components/GroupManagement.tsx, src/components/Notifications.tsx, src/notify-middleware.ts, src/styles/_buttons.scss, src/translation/defaultMessages/errors.tsx, src/translation/extractedMessages.json, src/translation/messageIndex.js
add error messages, clean up the code and disable the button when the user is unable to get the group (when they encounter an access denied error)
=> Eunju add SCIM error msg

src/components/GroupManagement.tsx, src/styles/_groupManagement.scss, src/styles/_typography.scss, src/translation/extractedMessages.json
Clearer import excel instructions
=> Cat toggle add section

src/apis/gnap/continueRequest.ts, src/apis/scim/groupsRequest.ts, src/apis/scim/usersRequest.ts, src/components/Callback.tsx, src/components/CreateAccounts.tsx, src/components/GroupManagement.tsx, src/components/ManagedAccountsApp.tsx, src/components/MembersList.tsx, src/components/StartSession.tsx, src/initLocalStorage.ts, src/initSessionStorage.ts, src/slices/appReducers.ts
- refactoring of StartSession() and initLocalStorage(). requestAccess() moved to StartSession()
- Callback component cleans the localStorage
- reset appSlice.isLoaded to null when starting the app or logging out
- use SessionStorage instead of LocalStorage
- save accessToken in store, update code
- move dispatch updateAccessToken inside useEffect
- fixed readonly handleGroupVersion i MembersListTypes
=> Ale cleaning code

src/components/MembersList.tsx, src/components/MembersListTable.tsx, src/translation/extractedMessages.json, src/translation/languages/sv.json
Changed column Username/EPPN to Username. Export Excel has two coumns for Username and EPPN
=> Changed column Username/EPPN to Username. Export Excel has two coumns for Username and EPPN

src/components/CreateAccounts.tsx, src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/styles/_ResetPassword.scss, src/styles/_buttons.scss, src/styles/_groupManagement.scss, src/styles/_inputs.scss
Copy edits, 
disabled label/button styling,
removed fieldsets and labels on create account and form controls after Wave testing,
improved visible element focus when tabbing.
=> Cat accessibility

src/apis/scim/error.ts, src/apis/scim/groupsRequest.ts, src/apis/scim/usersRequest.ts, src/components/GroupManagement.tsx, src/components/ManagedAccountsApp.tsx, src/notify-middleware.ts, src/slices/appReducers.ts
- changed scim apis actions to scim/
- removed handleErrorResponse() and instead throw scimResponse
- in notify-middleware filter action after scim and manage there 401 error
- added forcedLogout in appReducers
- in GroupManagement use forcedLogout to redirect to landing page
=> In middleware

src/components/CreateAccounts.tsx
fixed warning from sonarlint:
```
Promise returned in function argument where a void return was expected.sonarlint(typescript:S6544)
function(sheet: ExcelJS.Worksheet, id: number): Promise<void>
```
=> fixed with IIFE (Immediately Invoked Function Expression)

src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/components/MembersListTable.tsx, src/slices/getUsers.ts
- MembersListTable read and sort directly from the store
- "selected" property is added to ExtendedUserResponse type
- sorting methods are moved to getUsersSlice as reducers
- created a setSelected and seAllSelected reducers in getUsersSlice
- it seems to resolve the error:
`Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`
=> Use always members in store

src/components/CreateAccounts.tsx, src/components/GroupManagement.tsx, src/components/MembersList.tsx, src/components/MembersListTable.tsx, src/slices/getUsers.ts
- handleGroupVersion() runs again getState() after reloadMembersDetails()
- added getState() to copyToClipboardAllMembers() removeSelectedUser() exportExcel()
- added isFetching() to copyToClipboardAllMembers() exportExcel()
- added handleGroupVersion() to copyToClipboardAllMembers()
- transformed addPassword() into setAccountState()
=> Added getState() inside functions

src/apis/gnap/continueRequest.ts, src/apis/gnap/requestAccess.ts, src/components/Callback.tsx, src/components/CreateAccounts.tsx, src/components/GroupManagement.tsx, src/components/MembersListTable.tsx, src/components/StartSession.tsx, src/initSessionStorage.ts, src/slices/getUsers.ts
- setAccountsState() takes now the whole array of AccountState to be processed in store to be more efficient
- random_generated_kid not hardcoded and saved/read in sessionStorage
- when try/catch use console.error() instead of console.log()
- fixed some types
=> Last fixes

src/components/GroupManagement.tsx, src/components/StartSession.tsx, src/styles/_base.scss, src/styles/_typography.scss, src/translation/extractedMessages.json
- add a message when there is not accounts in the group
- MembersListIntro shows always
=> Add a message when there is not accounts in the group

src/components/GroupManagement.tsx
run checkAllMembersDetailsAreLoaded() before operating any changes (404 fix) to group
=> run checkAllMembersDetailsAreLoaded() before operating any changes (404 fix) to group

src/components/MembersListTable.tsx, src/translation/extractedMessages.json
=> Add created date
